### ISSUE TITLE
pterodactyl wont assign the right ip for it self?

### ISSUE THREAD

**Issue by maxtraxv3** [SalSevenSix/serverjockey#10]
![image](https://github.com/SalSevenSix/serverjockey/assets/12743527/fc419a8d-8253-4eb1-90f7-48006dd2bfc3)

nothing show up on http://192.168.8.192:8088

and it seem to set it self to  http://172.18.0.2:8088 and http://0.0.0.0:8088

(this isnt running on VM its on baremetal install of ubuntu server 22.04.1

**Comment by maxtraxv3** [comment]
seems was thing on my router nvm fixed.

**Comment by SalSevenSix** [comment]
Note that the IP shown in the console is the local IP for the Docker container. Same in the Ptero console because it uses Docker.
Ptero itself in the top-right corner shows the actual hosts local IP, which is the IP to use.

I don't have any immediate plans to make the IP shown in the console be the host IP not the container IP. Because it may not be easy and the expectation is that people using Docker or Ptero are going to be more technically knowledgeable. I expect them to know what IP is what.

**Comment by maxtraxv3** [comment]
i understand it just fine, how you can tell this is in the fist line.

**Comment by SalSevenSix** [comment]
Not sure what you are asking but if you mean how can I tell what IP am am looking at then....
If you have worked with docker you would notice that it uses IP addresses starting with 172
Most routers use LAN addresses starting with 192.168 or sometimes 10.0
Also if you see 0.0.0.0 that's not a real address, it means the all the IPs are bound. Meaning in your case connections can be made using 192.168.8.138:8088 or 127.0.0.1:8088 (i.e. localhost) however the latter can only be done locally.

**Comment by maxtraxv3** [comment]
0.0.0.0 typicaly mean it lisning to any ip.
im well aware of how IPs work Electrotechnology cert 2, even subnetmasks.

also been playing with networks since high school, by passed there systems even sent an email from the admins home to his server in school from him self, witch when check looked legit because of the IPs.
