### ISSUE TITLE
404 forbidden when trying to Wget the lastest Server Jocky.

### ISSUE THREAD

**Issue by maxtraxv3** [SalSevenSix/serverjockey#13]
![image](https://github.com/SalSevenSix/serverjockey/assets/12743527/d0950c61-c1ad-4c4f-85b6-5b42cb894e7a)

running via sudo gives same error.

**Comment by SalSevenSix** [comment]
Weird. It works in a browser but not using wget. I will have a look. May need to host elsewhere.

**Comment by SalSevenSix** [comment]
Looks like OneDrive has issues with downloads not providing a referrer. Thanks Microsoft.... https://unix.stackexchange.com/questions/139698/why-would-curl-and-wget-result-in-a-403-forbidden

Anyhow I re-hosted the DEB and RPM file to Catbox. Because it's simple and free. I tested it with wget and it's working fine now. I will look at better hosting tomorrow because although Catbox is convenient it's blocked in many place.

**Comment by SalSevenSix** [comment]
So I finally re-hosted the DEB and RPM files onto Oracle OCI. Tested with wget again and it's working fine. Browsers may give warning because redirect is from https to http, but that's fine. Closing issue.
