### ISSUE TITLE
Zombie Fix v2 manual install?

### ISSUE THREAD

**Issue by maxtraxv3** [SalSevenSix/serverjockey#16]
nvm

also any chance of minecraft jav support?

**Comment by SalSevenSix** [comment]
To answer your original question about modifying the game engine files to install a mod...

The system is designed to cover 95% of use cases, more oriented towards novice & intermediate hosts. So there is no easy way to meddle with the game service install itself, by design. You will have to login to the machine and use **root** or **sjgms** use to access those files. OR use the backup & restore feature as I covered here ->https://github.com/SalSevenSix/serverjockey/issues/15#issuecomment-1837093295

I looked at supporting Minecraft Java. However the JVM install makes it a bit more complicated. Also there are a big community/ecosystem around hosting the game. For example Ptero itself supports it, they have an Egg for Minecraft. However I will look at it again.
